"""
Templates for meeting brief generation.
"""

MEETING_BRIEF_TEMPLATE = """# Meeting Brief: {title}

**When:** {date_time}
**Duration:** {duration}
{location_line}

---

## Attendees

{attendees_section}

---

## Context

{context_section}

---

## Suggested Talking Points

{talking_points}

---

*Generated by Sol Unified Agent at {generated_at}*
"""

ATTENDEE_TEMPLATE = """### {name}
{role_line}
{notes_line}
{tags_line}
"""

NO_CRM_ENTRY = """- **Note:** Not in your People CRM. Consider adding them after the meeting.
"""
